Add functional test
Signed-off-by: Dong Zhu <bluezhudong@gmail.com>

diff --git a/wercker.yml b/wercker.yml
--- a/wercker.yml
+++ b/wercker.yml
@@ -28,3 +28,24 @@ deploy-to-oke:
         token: $KUBERNETES_TOKEN
         insecure-skip-tls-verify: true
         command: apply -f $WERCKER_ROOT/kubernetes-deployment.yml --namespace=$APP_NAMESPACE
+
+functional-test:
+  box:
+    id: openjdk:8-alpine 
+  steps:
+    - script:
+        name: Run Test
+        code: |
+            apk add maven
+            mvn install:install-file -Dfile=lib/ojdbc8.jar -DgroupId=com.oracle.jdbc -DartifactId=ojdbc8 -Dversion=18.3 -Dpackaging=jar
+            mvn clean package
+            exit_status=$?
+            echo "### start test ###"
+            #timeout -t 10 java -jar target/travel-agency-flight-0.0.1-SNAPSHOT.jar
+            #exit_status=$?
+            if [ $exit_status -eq 0 ]; then
+              echo "### test passed ###"
+            else
+              echo "### test failed ###"
+              exit -1
+            fi
